### ISSUE TITLE
REQ: Support voor LSC Smart Connect (Action)

### ISSUE THREAD

**Issue by PhAnt0mFS** [rebtor/nl.rebtor.tuya#1]
Action has start selling LSC Smart Connect which looks like Tuya devices. 
Support for this would be very nice.

[https://www.action.com/nl-nl/lsc-smart-connect/](url)

**Comment by seegersnl** [comment]
Should be great, bought some of the lights and they work great via the tuya iphone app. Love to see support for homey👍🏻

**Comment by rebtor** [comment]
Any particular devices you want to use? I think the plug will work with the neocam devices.  I will check if i can get my hands on some of these devices but i'm not going to buy them all. 

Of course anyone is welcome to do a pull request to add more devices.

**Comment by rebtor** [comment]
Added the plug and the RGB strip.
