### ISSUE TITLE
LSC Smart Connect Ledstrip can change color but won't turn on/off

### ISSUE THREAD

**Issue by wrdx** [rebtor/nl.rebtor.tuya#13]
I've connected an LSC Smart Connect Ledstrip to Homey via this app, following the setup instructions, but it seems to only half work.

I can change RGB colors without issue.

I can not turn the strip on or off.

I can not select a white tone, when selecting to the white color wheel (in the Homey device) the ledstrip switches to the white LED's but changing the tone from warm to cool won't change the tone on the ledstrip.

I'm running Homey v4.2.0 and v1.1.6 of this app.

**Comment by wrdx** [comment]
If it helps I can help you debug (installing test versions via cli, providing info etc).

**Comment by Milanzor** [comment]
@rebtor Do you have any news on this issue? I also have this problem.

**Comment by rebtor** [comment]
In the latest testbuild @ homey appstore this is fixed. I will update the repository later this week.

**Comment by Milanzor** [comment]
@rebtor Nice, thanks for the message, unfortunatly it seems incompatible with my Homey version. Is that something you could fix? I have other devices that don't work on the newer firmware yet.

**Comment by agerrmann** [comment]
@rebtor not to push you, but will this issue be solved? Would be great! Regards André

**Comment by mhoogenbosch** [comment]
This issue has been solved. Either download 2.0.2 from github or install the stable version, add the strip and upgrade to test branch which is 2.0.5. Then it works. Can't install it in 2.0.5, see issue.
