### ISSUE TITLE
Adding devices is mixed up / LSC devices

### ISSUE THREAD

**Issue by mhoogenbosch** [rebtor/nl.rebtor.tuya#14]
Starting with version above 2.0.2 (can't find anything after 2.0.2 on github, like the 2.0.5 currently on test branch) the LSC Smart Power Plug and LSC Smart LED Light Strip have been swapped. Can't add either.

**Comment by rebtor** [comment]
Fixed this, and i have downloaded the latest binaries to github. Homey moved away from Github will keep it updated for the forks.
