### ISSUE TITLE
Normal LSC light bulb

### ISSUE THREAD

**Issue by mhoogenbosch** [rebtor/nl.rebtor.tuya#15]
There is a LSC Smart Filament LED E27 bulb, but not the normal one with just white. I can add it, but it doesn't turn on or off.

NEW DATA ATRIBUTE: {“devId”:“085484012462ab4c0d80”,“dps”:{“20”:false,“21”:“white”,“22”:35,“23”:870,“25”:“000e0d0000000000000000c80000”,“26”:0,“101”:true}}

**Comment by rebtor** [comment]
Hi, 

What is the exact type of this led (because the normal filament led is already supported) and what are the attributes that change when you turn it on / off.

**Comment by mhoogenbosch** [comment]
Yes, this isn’t a filament led, but a normal/ regular E27 bulb. It’s the cheapest bulb from the line.

If needed I can  provide some photo’s or info on the bulb?

Verzonden vanuit Mail<https://go.microsoft.com/fwlink/?LinkId=550986> voor Windows 10

Van: ***@***.***>
Verzonden: zondag 2 mei 2021 15:09
Aan: ***@***.***>
CC: Martijn ***@***.***>; ***@***.***>
Onderwerp: Re: [rebtor/nl.rebtor.tuya] Normal LSC light bulb (#15)


Hi,

What is the exact type of this led (because the normal filament led is already supported) and what are the attributes that change when you turn it on / off.

**Comment by rebtor** [comment]
fixed
