### ISSUE TITLE
Can't get the ID and Key Pairs

### ISSUE THREAD

**Issue by DarkCinema** [rebtor/nl.rebtor.tuya#2]
I can't get the ID and Key pairs from my devices using the setup instructions from the TUYAPI. 
I don't know why, the AnyProxy seems to work for web pages but does noet work for the app.

Is their any other way to get the information needed?

**Comment by rebtor** [comment]
Hi. Yeah getting the key isn't fun. Changed the readme on this one. 

1. First of all try an android device (if you have one) 
2. On this topic alternatives are suggested and a fix for android is posted.  
https://github.com/codetheweb/tuyapi/issues/215 for possible solutions.
