### ISSUE TITLE
No package.json available

### ISSUE THREAD

**Issue by ricardovanlaarhoven** [rebtor/nl.rebtor.tuya#24]
There is no package.json in the repositorie and when i run `npm i` `p-timeout` is not installed.
Perhaps this project can be enhanced when the package.json is correct

**Comment by ricardovanlaarhoven** [comment]
Ah the tuyaapi is just copied in this project. So i should run npm i in that folder.
Perhaps it's better to get tuyaapi as a dependency? https://www.npmjs.com/package/tuyapi

**Comment by rebtor** [comment]
Fixed
