### ISSUE TITLE
Wifi Light Switches 

### ISSUE THREAD

**Issue by Abarth695** [rebtor/nl.rebtor.tuya#3]
Hi
Are you going to do more work on this area
Would be good to have Smart Life enabled wifi light and power switches and pir sensors  added

**Comment by hallard** [comment]
+1 bought WiFi LSC led filament, awesome device by the way could be great to drive them with homey

**Comment by rebtor** [comment]
The LSC filament led is supported. 
pir is not going to work since its battery powered. wifi light you could test by trying to add it as an of / off device like a powerplug. If it works i am willing to add the device officialy with the correct icons ect.
