### ISSUE TITLE
Tuya Smart Life APP Wireless video doorbell WIFI 1080P Camera 

### ISSUE THREAD

**Issue by konradwalsh** [rebtor/nl.rebtor.tuya#4]
Any chance you would add this...

is it possible...

Tuya Smart Life APP Wireless video doorbell WIFI 1080P Camera 

https://www.aliexpress.com/item/32975669793.html?spm=a2g0o.productlist.0.0.440e7c433aq987&s=p&algo_pvid=16475cfd-2c71-414d-8dfa-82e5406eb2ea&algo_expid=16475cfd-2c71-414d-8dfa-82e5406eb2ea-25&btsid=121ab99f-d6f5-4e2e-b228-039c3b98f88a&ws_ab_test=searchweb0_0,searchweb201602_9,searchweb201603_55

**Comment by rebtor** [comment]
This device is not supported by the TuyAPI this app is based on so i don't think this is going to work anytime soon.
